-- 1. Buat Tabel Venues (GOR)
CREATE TABLE IF NOT EXISTS public.venues (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  location TEXT NOT NULL,
  city TEXT NOT NULL,
  price_per_hour INTEGER NOT NULL,
  rating DECIMAL(2,1) DEFAULT 0.0,
  image_url TEXT,
  category TEXT DEFAULT 'Badminton',
  features TEXT[] DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Aktifkan RLS agar data aman
ALTER TABLE public.venues ENABLE ROW LEVEL SECURITY;

-- 3. Kebijakan agar semua orang bisa melihat daftar lapangan
CREATE POLICY "Izinkan Semua Orang Melihat Venue" ON public.venues FOR SELECT USING (true);

-- 4. Buat Tabel Courts (Sub-lapangan di dalam GOR)
CREATE TABLE IF NOT EXISTS public.courts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id BIGINT REFERENCES public.venues(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  type TEXT DEFAULT 'Vinyl',
  is_indoor BOOLEAN DEFAULT true,
  image_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.courts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Izinkan Semua Orang Melihat Court" ON public.courts FOR SELECT USING (true);

-- 5. Masukkan Data Contoh (Dummy Data)
INSERT INTO public.venues (name, location, city, price_per_hour, rating, image_url, category)
VALUES 
('Kalam Kudus Sport Center', 'Kota Surakarta, Jawa Tengah', 'Surakarta', 25000, 4.9, '/asset/kalam-kudus.png', 'Badminton'),
('Bengawan Sport Center', 'Kota Surakarta, Jawa Tengah', 'Surakarta', 15000, 4.8, '/asset/bengawan-sport.png', 'Badminton'),
('Surabaya Badminton Hall', 'Kota Surabaya, Jawa Timur', 'Surabaya', 165000, 4.7, '/asset/surabaya-badminton.png', 'Badminton'),
('GOR Arak Surabaya', 'Kota Surabaya, Jawa Timur', 'Surabaya', 165000, 4.6, '/asset/gor-arek-surabaya.png', 'Badminton');

-- Masukkan Data Court (Hubungkan ke ID Venue)
-- Catatan: ID 1 biasanya otomatis milik Kalam Kudus jika tabel baru dibuat
-- 6. Buat Tabel Matches (Main Bareng)
CREATE TABLE IF NOT EXISTS public.matches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_name TEXT NOT NULL,
  city TEXT NOT NULL,
  match_date DATE NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  skill_level TEXT DEFAULT 'Bebas',
  price_per_person INTEGER DEFAULT 0,
  gender_requirement TEXT DEFAULT 'Campur',
  image_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.matches ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Izinkan Semua Orang Melihat Match" ON public.matches FOR SELECT USING (true);

-- 7. Buat Tabel Bookings (Riwayat Pemesanan)
CREATE TABLE IF NOT EXISTS public.bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_email TEXT NOT NULL,
  venue_name TEXT NOT NULL,
  court_name TEXT NOT NULL,
  booking_date DATE NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  total_price INTEGER NOT NULL,
  status TEXT DEFAULT 'Lunas',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "User bisa melihat booking miliknya sendiri" ON public.bookings FOR SELECT USING (true); -- Untuk MVP kita izinkan dulu

-- Dummy Data Bookings (Contoh riwayat untuk user)
INSERT INTO public.bookings (user_email, venue_name, court_name, booking_date, start_time, end_time, total_price, status)
VALUES 
('user@example.com', 'Kalam Kudus Sport Center', 'Badminton Blue Court 1', '2026-03-06', '19:00:00', '20:00:00', 250000, 'Lunas'),
('user@example.com', 'Bengawan Sport Center', 'Bengawan Main Court', '2026-03-10', '16:00:00', '18:00:00', 30000, 'Lunas');
