ALTER TABLE partners ADD COLUMN IF NOT EXISTS phone TEXT;
ALTER TABLE partners ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE partners ADD COLUMN IF NOT EXISTS city TEXT;
ALTER TABLE partners ADD COLUMN IF NOT EXISTS maps_url TEXT;
ALTER TABLE partners ADD COLUMN IF NOT EXISTS open_time TEXT DEFAULT '08:00';
ALTER TABLE partners ADD COLUMN IF NOT EXISTS close_time TEXT DEFAULT '23:00';
ALTER TABLE partners ADD COLUMN IF NOT EXISTS price_day INTEGER DEFAULT 35000;
ALTER TABLE partners ADD COLUMN IF NOT EXISTS price_night INTEGER DEFAULT 50000;
ALTER TABLE partners ADD COLUMN IF NOT EXISTS payment_method TEXT DEFAULT 'Semua Metode (Transfer, E-Wallet, Tunai)';
